### ISSUE TITLE
Не работает "WEF: Ссылки"

### ISSUE THREAD

**Issue by vladiscripts** [vlsergey/WE-Framework#12]
Не работает практически во всех крупных статьях, где был указан нормативный контроль: код NDL (P349), LCNAF (P244), VIAF (P214), и др.

Тема на СО WE-Framework:
https://ru.wikipedia.org/wiki/%D0%9E%D0%B1%D1%81%D1%83%D0%B6%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5_%D0%92%D0%B8%D0%BA%D0%B8%D0%BF%D0%B5%D0%B4%D0%B8%D0%B8:WE-Framework#.22WEF:_.D0.A1.D1.81.D1.8B.D0.BB.D0.BA.D0.B8.22_.D0.BD.D0.B5_.D1.80.D0.B0.D0.B1.D0.BE.D1.82.D0.B0.D0.B5.D1.82_.D0.B2_.D1.81.D1.82.D0.B0.D1.82.D1.8C.D0.B5

**Comment by vlsergey** [comment]
fixed
