### ISSUE TITLE
Duplication of statements

### ISSUE THREAD

**Issue by JAnDud** [vlsergey/WE-Framework#14]
When using FEF: Links and adding VIAF, some more IDs are filled automatically too.
But when I save it, previously present IDs are now duplicated:
https://www.wikidata.org/w/index.php?title=Q453571&diff=next&oldid=418697675

**Comment by vlsergey** [comment]
Seems like long-living problem after converting strings to externalIds... will try to take care of it

**Comment by vlsergey** [comment]
shall be fixed now

**Comment by JAnDud** [comment]
seems OK
