### ISSUE TITLE
Add P268 (Bnf ID)

### ISSUE THREAD

**Issue by hsarrazin** [vlsergey/WE-Framework#17]
Could you please add P268 (Bnf ID) to 3rd tab (Classification) - it is a French reference, much more used than SUDOC, and both should be next to each other.. .

thanks a lot :)

**Comment by belett** [comment]
+1, it's *the* reference for books in France.

For clarity, this would be for FRBR Edition.

**Comment by vlsergeyatsbt** [comment]
It's added and also can be autocomplete using VIAF lookup feature

**Comment by hsarrazin** [comment]
Hello @vlsergeyatsbt @belett 

VIAF lookup is for Biographies only...

But P268 is not only for author's authorities, it is also used for Works and Editions (it is a library Catalog, not just an authorities reference)

Could you please add it to both FRBR-Editions and FRBR-Works ? 

Thanks for your help on this. For French librarians it is MUCH more important than P3631 (which is a publicly contributed base, and therefore not as reliable, and much less complete :)
