### ISSUE TITLE
clarify license

### ISSUE THREAD

**Issue by ricordisamoa** [vlsergey/WE-Framework#2]
This repository only specifies the GNU GPLv2.
However, publishing it [on Wikipedia](https://ru.wikipedia.org/wiki/MediaWiki:Gadget-wefcore.js) would imply that it is also available under the Creative Commons Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.

**Comment by vlsergey** [comment]
whenever author (i.e. myself) publishes it on Wikipedia distribution is dual-licenced implicitly. But only for published versions.
