### ISSUE TITLE
in Work module, replace P364 by P407

### ISSUE THREAD

**Issue by hsarrazin** [vlsergey/WE-Framework#21]
P364 has been deprecated and is in the process of replacement by P407 on Work items, but P364 is still the property used in FRBR Work. Could you please replace it ? (or, to ease the conversion, add it just under it) ?

Thanks for the recent improvements on this tool. It's becoming really swift and easy :)

**Comment by vlsergey** [comment]
replaced, deployed

**Comment by hsarrazin** [comment]
Thanks !
