### ISSUE TITLE
add P1922 (incipit) to both edition and work module ?

### ISSUE THREAD

**Issue by hsarrazin** [vlsergey/WE-Framework#23]
Hello, 
for cataloguing poems (wikisource mainly), P1922 is very useful. Could you please add it to both Edition and Work modules (since we add it on work but also translated editions), in the content tab ?
Thanks a lot :)

**Comment by vlsergeyatsbt** [comment]
commited, but not deployed yet

**Comment by vlsergey** [comment]
deployed
