### ISSUE TITLE
Still P268

### ISSUE THREAD

**Issue by hsarrazin** [vlsergey/WE-Framework#24]
Hello @vlsergeyatsbt - you close issue #17 (and I don't know how to re-open it), but VIAF lookup is for Biographies only...

We need  P268 not only for author's authorities, but also for Works and Editions (it is a library Catalog, not just an authorities reference)

Could you please add it to both FRBR-Editions and FRBR-Works ?

Thanks for your help on this. For French librarians it is MUCH more important than P3631 (which is a publicly contributed base, and therefore not as reliable, and much less complete :)

Thanks

@Belett

**Comment by vlsergeyatsbt** [comment]
@hsarrazin , VIAF lookup is present in "External Links" editor on "VIAF" tab. So feel free to use it for any entity.

**Comment by hsarrazin** [comment]
@vlsergeyatsbt you don't understand... 
I don't need VIAF lookup... VIAF is for people and organization, not for books and works, and definitely cannot help me adding  P268 to works or editions. 

What I would like is that you add P268 to the authority tab on FRBR-Editions and FRBR-Works, so that I can add it, or check it, without having to leave wikisource to go on wikidata each time. 
It is different from P4258, because it does not link to a scan of the book but to the catalog entry of a book... see https://www.wikidata.org/wiki/Q57246049 to see what I mean. 
Please, just add the ID to the tab, it is #1 reference for french librarians. Thanks
