### ISSUE TITLE
Did you recently change P31 default values when creating an item ?

### ISSUE THREAD

**Issue by hsarrazin** [vlsergey/WE-Framework#25]
Hello, when creating an item from the link, as article, FRBR-edition or FRBR-book, on P31 list, I now have a list of values that are not my recently used values but default (album, building, firm, movie, book, house, family name, painting, ... human being, human settlement), which are mostly and obviously wrong for the type of items I work on... and that I will probably never use…
But the values I recently used, that were very useful to me because I always use 5 or 6 ones, have disappeared. 
Did you recently changed something in the behaviour when creating an item ? or is it something that happened on my browser ?

Thanks for your help on this.

Is there a way I can reset the list for P31 ? (for other values, there is no problem, my recently used values are still in the list)

**Comment by vlsergey** [comment]
It was because of this change to P31 property: https://www.wikidata.org/w/index.php?title=Property:P31&diff=768008766&oldid=766758092

Now it's reverted

**Comment by hsarrazin** [comment]
Hello. 
After going back to previous behaviour (Nice!), which allowed to used personal frequently used values, you finally went back... and it's showing again these values, that are 100% wrong for items created from wikisource, where I mostly use Q3331189 as P31 on FRBR-edition items... the default value you put is Q732577 (which is NOT the recommended value for FRBR-edition, according to https://www.wikidata.org/wiki/Wikidata:WikiProject_Books#Edition_item_properties).
As a consequence, I have to manually change to Q3331189 on all items I create for wikisource texts (and I have thousands of them to do). 
Why did you do this ? I do not understand why ? was it accidental regression ? if not, could you please explain me why ? 
As it is now, the FRBR-edition is NOT useful, and makes me loose a lot of time. 

Thanks for your help on this.

**Comment by vlsergey** [comment]
@hsarrazin , will update to Q3331189 for FRBR-edition

**Comment by hsarrazin** [comment]
Thanks a lot !!!
